export const dummyCars = [
  {
    owner: "67fe3467ed8a8fe17d0ba6e2",
    brand: "BMW",
    model: "X5",
    image: "https://ik.imagekit.io/hary/car_image1.png?updatedAt=1751529596764",
    year: 2006,
    category: "SUV",
    seating_capacity: 4,
    fuel_type: "Hybrid",
    transmission: "Semi-Automatic",
    pricePerDay: 300,
    location: "New York",
    description: "The BMW X5 is a mid-size luxury SUV produced by BMW.",
    isAvaliable: true,
  },
  {
    owner: "67fe3467ed8a8fe17d0ba6e2",
    brand: "Toyota",
    model: "Corolla",
    image: "https://ik.imagekit.io/hary/car_image2.png?updatedAt=1751529594759",
    year: 2021,
    category: "Sedan",
    seating_capacity: 4,
    fuel_type: "Diesel",
    transmission: "Manual",
    pricePerDay: 130,
    location: "Chicago",
    description:
      "The Toyota Corolla is a mid-size luxury sedan produced by Toyota.",
    isAvaliable: true,
  },
  {
    owner: "67fe3467ed8a8fe17d0ba6e2",
    brand: "Mercedes",
    model: "C-Class",
    image: "https://ik.imagekit.io/hary/car_image3.png?updatedAt=1751529595737",
    year: 2019,
    category: "Sedan",
    seating_capacity: 5,
    fuel_type: "Petrol",
    transmission: "Automatic",
    pricePerDay: 200,
    location: "Los Angeles",
    description:
      "The Mercedes-Benz C-Class is a premium sedan known for comfort and performance.",
    isAvaliable: true,
  },
  {
    owner: "67fe3467ed8a8fe17d0ba6e2",
    brand: "Tesla",
    model: "Model 3",
    image: "https://ik.imagekit.io/hary/car_image4.png?updatedAt=1751529586337",
    year: 2023,
    category: "Sedan",
    seating_capacity: 5,
    fuel_type: "Electric",
    transmission: "Automatic",
    pricePerDay: 350,
    location: "San Francisco",
    description:
      "The Tesla Model 3 is an all-electric sedan with cutting-edge technology.",
    isAvaliable: true,
  },
  {
    owner: "67fe3467ed8a8fe17d0ba6e2",
    brand: "Jeep",
    model: "Wrangler",
    image: "https://ik.imagekit.io/hary/car_image3.png?updatedAt=1751529595737",
    year: 2023,
    category: "SUV",
    seating_capacity: 4,
    fuel_type: "Hybrid",
    transmission: "Automatic",
    pricePerDay: 200,
    location: "Los Angeles",
    description:
      "The Jeep Wrangler is a luxury SUV known for its off-road capabilities.",
    isAvaliable: true,
  },
  {
    owner: "67fe3467ed8a8fe17d0ba6e2",
    brand: "Ford",
    model: "Neo 6",
    image: "https://ik.imagekit.io/hary/car_image4.png?updatedAt=1751529586337",
    year: 2022,
    category: "Sedan",
    seating_capacity: 2,
    fuel_type: "Diesel",
    transmission: "Semi-Automatic",
    pricePerDay: 209,
    location: "Houston",
    description: "A luxury sedan known for comfort and efficiency.",
    isAvaliable: true,
  },
  {
    owner: "67fe3467ed8a8fe17d0ba6e2",
    brand: "Audi",
    model: "Q7",
    image: "https://ik.imagekit.io/hary/car_image2.png?updatedAt=1751529594759",
    year: 2019,
    category: "SUV",
    seating_capacity: 7,
    fuel_type: "Petrol",
    transmission: "Automatic",
    pricePerDay: 350,
    location: "Los Angeles",
    description:
      "The Audi Q7 is a luxurious full-size SUV offering advanced technology.",
    isAvaliable: true,
  },
  {
    owner: "67fe3467ed8a8fe17d0ba6e2",
    brand: "Mercedes-Benz",
    model: "S-Class",
    image: "https://ik.imagekit.io/hary/car_image1.png?updatedAt=1751529596764",
    year: 2022,
    category: "Sedan",
    seating_capacity: 5,
    fuel_type: "Petrol",
    transmission: "Automatic",
    pricePerDay: 500,
    location: "Dubai",
    description:
      "The Mercedes S-Class offers unmatched luxury and performance.",
    isAvaliable: false,
  },
  {
    owner: "67fe3467ed8a8fe17d0ba6e2",
    brand: "Tesla",
    model: "Model X",
    image: "https://ik.imagekit.io/hary/car_image2.png?updatedAt=1751529594759",
    year: 2021,
    category: "Electric SUV",
    seating_capacity: 5,
    fuel_type: "Electric",
    transmission: "Automatic",
    pricePerDay: 450,
    location: "San Francisco",
    description:
      "The Tesla Model X features falcon wing doors and autopilot capabilities.",
    isAvaliable: true,
  },
  {
    owner: "67fe3467ed8a8fe17d0ba6e2",
    brand: "Porsche",
    model: "911",
    image: "https://ik.imagekit.io/hary/car_image1.png?updatedAt=1751529596764",
    year: 2018,
    category: "Sports Car",
    seating_capacity: 2,
    fuel_type: "Petrol",
    transmission: "Manual",
    pricePerDay: 600,
    location: "Miami",
    description:
      "The Porsche 911 is a timeless sports car with thrilling performance.",
    isAvaliable: true,
  },
  {
    owner: "67fe3467ed8a8fe17d0ba6e2",
    brand: "Lamborghini",
    model: "Huracán",
    image: "https://ik.imagekit.io/hary/car_image2.png?updatedAt=1751529594759",
    year: 2020,
    category: "Supercar",
    seating_capacity: 2,
    fuel_type: "Petrol",
    transmission: "Automatic",
    pricePerDay: 1000,
    location: "Monaco",
    description:
      "The Lamborghini Huracán delivers aggressive styling and extreme performance.",
    isAvaliable: false,
  },
];
